### ISSUE TITLE
License discovery issues

### ISSUE THREAD

**Issue by halostatue** [unnawut/licensir#2]
There are license discovery issues with licensir. The issue is basically the same as pivotal/LicenseFinder#465, except inverted. Some of the licenses appear to be found by LicenseFinder that are not found by licensir.

Note that the licensir output is truncated because LicenseFinder does not include (in its action items command) anything that has been whitelisted or otherwise ignored. There are a number of Elixir dependencies that LicenseFinder correctly finds as MIT, Apache 2.0, or ISC and does not output in the results. Licensir shows *more* `unknown` types than are shown in the output in pivotal/LicenseFinder#465.

**Comment by unnawut** [comment]
Hey thanks for reporting. I didn't know of `pivotal/LicenseFinder` before and oh wow that it looks great!

From a brief look, it seems that LicenseFinder downloads the dependencies and checks if some certain license files match a license's template. Licensir, on the other hand, simply collects the license value defined inside each `mix.exs` file and outputs them.

I doubt if LicenseFinder would ever parse `mix.exs` like licensir does, since they need to support multiple languages. While license file-checking sounds doable for licensir, it is not a small effort. 

I'm interested to implement this, and bring in a few goodies from LicenseFinder, but it will take weeks. If you want to have a shot at it before I do, please feel free to and let me know!

**Comment by unnawut** [comment]
Will start working on it this weekend

**Comment by unnawut** [comment]
Done! Please try again :)

```
def deps do
  [
    {:licensir, "~> 0.2.0", only: :dev, runtime: false}
  ]
end
```
